name: Deploy to App Engine on PR Events

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: write
  deployments: write

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet

      - name: Get App Engine URL
        id: get-url
        run: |
          URL=$(gcloud app browse -s github-actions --project=${{ secrets.GCP_PROJECT_ID }} --no-launch-browser)
          echo "url=$URL" >> $GITHUB_ENV

      - name: Post deployment comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: |
            ## Deployment Status
          message: |
            Deployment for [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) succeeded.
            Access the deployed application [here](${ url })

  destroy:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Destroy App Engine service
        run: |
          gcloud app services delete github-actions --quiet
